name: Deploy Application to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH Key Files
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: nodejs-hello-world

    - name: Terraform Validate
      run: terraform validate
      working-directory: nodejs-hello-world

    #Added configuration for Terraform State Remove
#    - name: Terraform State Remove
#      run: |
#        terraform state rm module.tier3_app
 #      terraform state rm module.tier3_app.azurerm_resource_group.rg
 #      terraform state rm module.tier3_app.azurerm_public_ip.frontend_pip
 #      terraform state rm module.tier3_app.azurerm_network_security_group.frontend_nsg
 #      terraform state rm module.tier3_app.azurerm_virtual_network.vnet
 #     working-directory: nodejs-hello-world
  
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: nodejs-hello-world

    - name: Terraform Import Resources
      run: | 
        terraform import module.tier3_app.azurerm_virtual_network.vnet "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/virtualNetworks/iac-vnet"
        terraform import module.tier3_app.azurerm_network_security_group.frontend_nsg "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/networkSecurityGroups/frontend-nsg"
        terraform import module.tier3_app.azurerm_public_ip.frontend_pip "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/publicIPAddresses/frontend-pip"
        terraform import module.tier3_app.azurerm_subnet.frontend "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/virtualNetworks/iac-vnet/subnets/frontend-subnet"
      working-directory: nodejs-hello-world

    - name: Terraform State List
      run: terraform state list
      working-directory: nodejs-hello-world

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: nodejs-hello-world

    - name: Verify Deployment
      run: curl http://${{ secrets.PUBLIC_IP }}